In [1]:
import pandas as pd

In [2]:
data=pd.read_excel(r"C:\Users\PIYUSH\Desktop\data\maindata.xlsx",sheet_name=None)

In [19]:
data2=pd.read_excel(r"C:\Users\PIYUSH\Desktop\data\Customers_31JAN2019.xlsx",sheet_name=None)

In [22]:
data_cust=data2['Sheet1']

In [16]:
data_main=data['LMS_HLLAP']

In [38]:
data_main.isnull()

,AGREEMENTID,CUSTOMERID,LOAN_AMT,NET_DISBURSED_AMT,CURRENT_ROI,ORIGNAL_ROI,CURRENT_TENOR,ORIGNAL_TENOR,DUEDAY,PRE_EMI_DUEAMT,...,PAID_INTEREST,MONTHOPENING,LAST_RECEIPT_AMOUNT,NET_LTV,COMPLETED_TENURE,BALANCE_TENURE,DPD,FOIR,SCHEMEID,MOB
count,6.242500e+05,6.237340e+05,6.242500e+05,6.242500e+05,624250.000000,624250.000000,624245.000000,624250.000000,624250.000000,6.242500e+05,...,6.242500e+05,6.242500e+05,6.122050e+05,624250.000000,624250.000000,624245.000000,624219.000000,624250.000000,6.237340e+05,624250.000000
mean,1.123081e+07,1.201179e+07,5.828204e+06,5.778192e+06,15.068840,14.997058,178.406491,177.910326,6.405117,6.221159e+04,...,9.637954e+05,5.442760e+06,4.855566e+04,48.825046,15.256937,163.149432,7.921803,21.479576,1.090119e+07,16.767239
std,7.984211e+03,7.961736e+03,1.323121e+07,1.313555e+07,2.506164,2.470942,49.490712,44.212338,3.533971,3.555793e+05,...,3.293273e+06,1.226295e+07,2.398423e+05,20.531984,15.549111,52.995329,65.112792,2687.131947,8.546587e+01,15.613276
min,1.122000e+07,1.200100e+07,3.753240e+04,3.753240e+04,-5.056636,0.000000,0.000000,0.000000,1.000000,0.000000e+00,...,0.000000e+00,0.000000e+00,1.000000e-02,0.380000,0.000000,0.000000,0.000000,-170.330000,1.090110e+07,0.000000
25%,1.122430e+07,1.200530e+07,1.516309e+06,1.501296e+06,13.109796,13.109796,150.000000,168.000000,5.000000,4.975868e+03,...,8.360153e+04,1.469379e+06,1.040000e+04,32.780000,3.000000,128.000000,0.000000,0.400000,1.090111e+07,5.000000
50%,1.122894e+07,1.200993e+07,2.627268e+06,2.593211e+06,14.982624,14.982624,180.000000,180.000000,5.000000,1.222875e+04,...,2.681067e+05,2.483012e+06,1.900000e+04,50.290000,10.000000,169.000000,0.000000,0.510000,1.090115e+07,12.000000
75%,1.123592e+07,1.201690e+07,5.209731e+06,5.166899e+06,17.167590,16.543314,203.000000,180.000000,5.000000,3.607449e+04,...,7.640072e+05,4.850362e+06,3.759200e+04,64.840000,23.000000,182.000000,0.000000,0.690000,1.090129e+07,24.000000
max,1.125335e+07,1.203390e+07,5.704924e+08,5.674589e+08,37.456560,34.147897,713.000000,300.000000,15.000000,3.177540e+07,...,1.845529e+08,5.674589e+08,8.496881e+07,104.860000,98.000000,693.000000,2268.000000,547616.000000,1.090146e+07,98.000000